### ISSUE TITLE
Loop limit

### ISSUE THREAD

**Issue by tremby** [missmatsuko/asl-tab#2]
It'd be good to limit the number of loops. I've opened a new tab and accidentally left it looping for some time a few times now.

**Comment by missmatsuko** [comment]
Thinking of using https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API to change the Iframe URL on visibility change to deal with this because Firefox doesn't like the Iframe Player API #3

**Comment by tremby** [comment]
That's a good idea but I think ideally it'd still limit the number of loops when in the foreground.
